syntax="proto3";
package txservice.remote;

option cc_generic_services = true;

message ConnectRequest {
  string message = 1;
};

message ConnectResponse {
  string message = 1;
};

message TransferRequest {
  uint32 ng_id = 1;
}

message TransferResponse {
  bool error = 1;
}

message CheckTxStatusRequest {
	uint64 tx_number = 1;
	int64 tx_term = 2;
}

message CheckTxStatusResponse {
    enum TxStatus {
		NOT_FOUND = 0;
		ONGOING = 1;
		COMMITTED = 2;
		ABORTED = 3;
		RESULT_UNKNOWN = 4;
	}
	TxStatus tx_status = 1;
}

// New leader notify its node_id to other nodes.
message NotifyNewLeaderStartRequest {
  uint32 ng_id = 1;
  uint32 node_id = 2;
}

message NotifyNewLeaderStartResponse {
  bool error = 1;
}

message GetMinTxStartTsRequest {
	uint32 ng_id = 1;
}

message GetMinTxStartTsResponse {
	int64 term = 1;
	uint64 ts = 2;
	bool error = 3;
}

service CcStreamService {
  rpc Connect(ConnectRequest) returns (ConnectResponse);
};

service CcRpcService {
	rpc Transfer(TransferRequest) returns (TransferResponse);
	rpc CheckTxStatus(CheckTxStatusRequest) returns (CheckTxStatusResponse);
	rpc NotifyNewLeaderStart(NotifyNewLeaderStartRequest) returns (NotifyNewLeaderStartResponse);
	rpc GetMinTxStartTs(GetMinTxStartTsRequest) returns (GetMinTxStartTsResponse);
}

message TxId_msg {
	uint32 core_id = 1;
	uint32 ident = 2;
	uint64 vec_idx = 3;
}

message CceAddr_msg {
	oneof entry_ptr {
		uint64 cce_ptr = 1;
		uint64 insert_ptr = 2;
	}
	int64 term = 3;
}

enum IsolationType {
	ReadCommitted = 0;
	SnapshotIsolation = 1;
	RepeatableRead = 2;
	Serializable = 3;
}

enum CcProtocolType {
	Occ = 0;
	OccRead = 1;
	Locking = 2;
}

enum CcLockType {
	NoLock = 0;
	ReadIntent = 1;
	WriteIntent = 2;
	ReadLock = 3;
	WriteLock = 4;
}

enum CcOperationType {
   	Read = 0;
    ReadForWrite = 1;
    Write = 2;
    ReadSkIndex = 3;
}

enum RecordStatusType {
	NORMAL = 0;
	UNDEFINED = 1;
	DELETED = 2;
	VERSIONUNDEFIND=3;
}

enum CommitType {
	PrepareCommit = 0;
	PostCommit = 1;
}

enum CcTableType {
    Primary = 0;
    Secondary = 1;
    Catalog = 2;
    RangePartition = 3;
}

message AcquireRequest {
	uint32 src_node_id = 1;
	string table_name_str = 2;
	CcTableType table_type = 3;
	bytes key = 4;
	uint32 key_shard_code = 5;
	uint32 vec_idx = 6;
	uint64 ts = 7;
	bool insert = 8;
	CcProtocolType protocol = 9;
	IsolationType iso_level = 10;
}

message AcquireResponse {
	int32 error_code = 1;
	uint64 vali_ts = 2;
	uint64 commit_ts = 3;
	CceAddr_msg cce_addr = 4;
	// The response is an acknowledgement or the result
	bool is_ack = 5;
	uint32 vec_idx = 6;
}

message AcquireAllRequest {
	uint32 src_node_id = 1;
	string table_name_str = 2;
	CcTableType table_type = 3;
  oneof acq_all_key
  {
	  bytes key = 4;
    bool neg_inf = 5;
    bool pos_inf = 6;
  }
	uint32 node_group_id = 7;
	bool insert = 8;
	CcProtocolType protocol = 9;
	CcOperationType cc_op = 10;
}

message AcquireAllResponse {
	int32 error_code = 1;
	uint64 vali_ts = 2;
	uint64 commit_ts = 3;
	int64 node_term = 4;
	// The response is an acknowledgement or the result
	bool is_ack = 5;
}

message ValidateRequest {
	uint32 src_node_id = 1;
	uint32 node_group_id = 2;
	CceAddr_msg cce_addr = 3;
	uint64 start_ts = 4;
	uint64 commit_ts = 5;
	uint64 key_ts = 6;
	uint64 gap_ts = 7;
	CcProtocolType protocol = 8;
	CcLockType lock_type = 9;
}

message ValidateResponse {
	int32 error_code = 1;
	repeated uint64 txs = 2;
}

message PostprocessResponse {
	int32 error_code = 1;
}

message VersionTxRecord_msg {
	bytes record = 1;
	RecordStatusType rec_status = 2;
	uint64 version_ts = 3;
}

message ReadRequest {
	uint32 src_node_id = 1;
	string table_name_str = 2;
	CcTableType table_type = 3;
	bytes key = 4;
	uint32 key_shard_code = 5;
	bytes record = 6;
	enum ReadType {
		INSIDE = 0;
		OUTSIDE_NORMAL = 1;
		OUTSIDE_DELETED = 2;
	}
	ReadType read_type = 7;
	uint64 ts = 8;
	IsolationType iso_level = 9;
	CcProtocolType protocol = 10;
	bool is_for_write = 11;
}

message ReadResponse {
	int32 error_code = 1;
	bytes record = 2;
	RecordStatusType rec_status = 3;
	uint64 ts = 4;
	CceAddr_msg cce_addr = 5;
	CcLockType lock_type = 6;
	// The response is an acknowledgement or the result
	bool is_ack = 7;
}

message ReadOutsideRequest {
    uint32 node_group_id = 1;
	bytes record = 2;
	RecordStatusType rec_status = 3;
	uint64 commit_ts = 4;
	CceAddr_msg cce_addr = 5;
	repeated VersionTxRecord_msg archives = 6;
}

message PostCommitRequest {
	uint32 src_node_id = 1;
	uint32 node_group_id = 2;
	CceAddr_msg cce_addr = 3;
	uint64 commit_ts = 4;
	bytes record = 5;
	uint32 operation_type = 6;
	CcProtocolType protocol = 7;
	uint32 key_shard_code = 8;
}

message PostWriteAllRequest {
	uint32 src_node_id = 1;
	string table_name_str = 2;
	CcTableType table_type = 3;
	uint32 node_group_id = 4;
  oneof post_write_key
  {
	  bytes key = 5;
    bool neg_inf = 6;
    bool pos_inf = 7;
  }
	uint64 commit_ts = 8;
	bytes record = 9;
	uint32 operation_type = 10;
	CommitType commit_type = 11;
}

message ScanTuple_msg {
	bytes key = 1;
	bytes record = 2;
	RecordStatusType rec_status = 3;
	uint64 key_ts = 4;
	uint64 gap_ts = 5;
	CceAddr_msg cce_addr = 6;
}

message ScanOpenRequest {
	uint32 src_node_id = 1;
	uint32 shard_id = 2;
	string table_name_str = 3;
	CcTableType table_type = 4;
	oneof start_key {
		bytes key = 5;
		bool neg_inf = 6;
		bool pos_inf = 7;
	}
	bool inclusive = 8;
	bool direction = 9;
	uint64 ts = 10;
	bool ckpt = 11;
	IsolationType iso_level = 12;
	CcProtocolType protocol = 13;
	bool is_for_write = 14;
}

message ScanCache_msg {
	repeated ScanTuple_msg scan_tuple = 1;
}

message ScanOpenResponse {
	int32 error_code = 1;
	uint32 node_group_id = 2;
	repeated ScanCache_msg scan_cache = 3;
}

message ScanNextRequest {
	uint32 src_node_id = 1;
	uint32 node_group_id = 2;
	uint64 prior_cce_ptr = 3;
	bool direction = 4;
	uint64 ts = 5;
	uint64 scan_cache_ptr = 6;
	bool ckpt = 7;
	IsolationType iso_level = 8;
	CcProtocolType protocol = 9;
	bool is_for_write = 10;
}

message ScanNextResponse {
	int32 error_code = 1;
	repeated ScanTuple_msg scan_tuple = 2;
	uint64 scan_cache_ptr = 3;
}

message FaultInjectRequest {
  uint32 src_node_id = 1;
  string fault_name = 2;
  string fault_paras = 3;
}

message FaultInjectResponse {
  int32 error_code = 1;
}

message CleanCcEntryForTestRequest {
  uint32 src_node_id = 1;
  string table_name_str = 2;
  CcTableType table_type = 3;
  bytes key = 4;
  uint32 key_shard_code = 5;
  bool only_archives=6;
  bool flush=7;
}

message CleanCcEntryForTestResponse {
  int32 error_code = 1;
}

message RecoverStateCheckRequest {
  uint32 src_node_id = 1;
  uint32 node_group_id = 2;
}

message RecoverStateCheckResponse {
  int32 error_code = 1;
  uint32 node_group_id = 2;
}

message BroadcastStatisticsRequest {
	uint32 src_node_id = 1;
	uint32 node_group_id = 2;
	string table_name_str = 3;
	bytes statistics_binary = 4;
}

message CcMessage {
	enum MessageType {
		Shutdown = 0;
		AcquireRequest = 2;
		AcquireResponse = 3;
		ReadRequest = 4;
		ReadResponse = 5;
		ValidateRequest = 6;
		ValidateResponse = 7;
		PostprocessResponse = 8;
		PostCommitRequest = 10;
		ScanOpenRequest = 12;
		ScanOpenResponse = 13;
		ScanNextRequest = 14;
		ScanNextResponse = 15;
		ReadOutsideRequest = 17;
		FaultInjectRequest = 26;
		FaultInjectResponse = 27;
		AcquireAllRequest = 28;
		AcquireAllResponse = 29;
		PostWriteAllRequest = 30;
		CleanCcEntryForTestRequest = 32;
		CleanCcEntryForTestResponse = 33;
		RecoverStateCheckRequest = 34;
		RecoverStateCheckResponse = 35;
		BroadcastStatisticsRequest = 36;
	}

	MessageType type = 1;
	uint64 tx_number = 2;
	uint64 handler_addr = 3;
	int64 tx_term = 4;
	uint32 command_id=5;

	oneof content {
		AcquireRequest acquire_req = 10;
		AcquireResponse acquire_resp = 11;
		ReadRequest read_req = 12;
		ReadResponse read_resp = 13;
		ValidateRequest validate_req = 14;
		ValidateResponse validate_resp = 15;
		PostprocessResponse post_resp = 16;
		PostCommitRequest postcommit_req = 18;
		ScanOpenRequest scan_open_req = 20;
		ScanOpenResponse scan_open_resp = 21;
		ScanNextRequest scan_next_req = 22;
		ScanNextResponse scan_next_resp = 23;
		ReadOutsideRequest read_outside_req = 25;
		FaultInjectRequest fault_inject_req = 34;
		FaultInjectResponse fault_inject_resp= 35;
		AcquireAllRequest acquire_all_req = 36;
		AcquireAllResponse acquire_all_resp = 37;
		PostWriteAllRequest post_write_all_req = 38;
		CleanCcEntryForTestRequest clean_cc_entry_req = 40;
		CleanCcEntryForTestResponse clean_cc_entry_resp= 41;
		RecoverStateCheckRequest recover_state_check_req = 42;
		RecoverStateCheckResponse recover_state_check_resp = 43;
		BroadcastStatisticsRequest broadcast_statistics_req = 44;
	}
}
